services:
  - type: web
    name: weight-tracker-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    build:
      packages:
        - tesseract-ocr
